### ISSUE TITLE
username/creds no longer working

### ISSUE THREAD

**Issue by fireheadman** [jjhuff/SmartThings_RheemEcoNet#1]
just purchased a water heater, thought I would try this app out.
unless I am doing something incorrectly, the creds are not working for me.

**Comment by jjhuff** [comment]
Unfortunately, this integration was with Rheem's old API. I'm no longer a smartthings user (switched to HomeAssistant), but I seem to recall that someone else in the forums made an updated version.

**Comment by fireheadman** [comment]
would be nice, similar to how the previous owner did to put a link on your github page to the new updated version

**Comment by jjhuff** [comment]
If you find one that works, go ahead and update this issue, and I'll add a link.
Thanks!

**Comment by zenkat** [comment]
I'm investigating the Rheem API for a project.  Do either of you know if an updated version for the new API was ever published?  And/or have either of you found good documentation links for the new API?  The available information out there is spotty.

Thanks in advance!

**Comment by jjhuff** [comment]
HomeAssistant supports the new API. I'm not sure if they found docs, or just reverse engineered it.
